server:
  port: ${PORT:8183}

app:
  qty:
    limit: 10
    enabled: true

spring:
  application:
    name: inventory
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

resilience4j:
  circuitbreaker:
    #    circuit-breaker-aspect-order: 1
    metrics:
      enabled: true
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 120
        slidingWindowType: TIME_BASED
        failureRateThreshold: 49
        slowCallDurationThreshold: 30000
        slowCallRateThreshold: 74
        permittedNumberOfCallsInHalfOpenState: 2
        #      maxWaitDurationInHalfOpenState: 0
        minimumNumberOfCalls: 4
        waitDurationInOpenState: 30000
        automaticTransitionFromOpenToHalfOpenEnabled: false
    instances:
      slowService:
        baseConfig: default
        slidingWindowSize: 120
      fastService:
        baseConfig: default
        slidingWindowSize: 60
  retry:
    #    retry-aspect-order: 2
    metrics:
      enabled: true
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
    instances:
      slowService:
        #        baseConfig: default
        maxAttempts: 5
        waitDuration: 500ms
      fastService:
        maxAttempts: 3
        waitDuration: 500ms

resilience4j.timelimiter:
  instances:
    backendA:
      timeoutDuration: 2s
      cancelRunningFuture: true
    backendB:
      timeoutDuration: 1s
      cancelRunningFuture: false

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, circuitbreakers, metrics
  endpoint:
    info:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
    defaults:
      enabled: true
    circuitbreakers:
      enabled: true
