server:
  port: ${PORT:8184}

app:
  cost:
    limit: 100

spring:
  application:
    name: payment

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info
  endpoint:
    info:
      enabled: true
    health:
      probes:
        enabled: true
      enabled: true
      show-details: always
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
    defaults:
      enabled: true
